Repository raynor-koh/Orbital23-24, pull requests merged in 2024-07, with the labels that each got.

#36 Add unit testing for userPositionHandler
  server/__tests__/handlers/authHandlers/authJWTTokenHandler.test.ts
  server/__tests__/handlers/authHandlers/authSignInHandler.test.ts
  server/__tests__/handlers/authHandlers/authSignUpHandler.test.ts
  server/__tests__/handlers/authHandlers/authTokenIsValidHandler.test.ts
  server/__tests__/handlers/userDataHandlers/userPositionHandlers.test.ts
  server/handlers/userdata/userPositionHandler.ts
  server/routes/user.ts
Labels: core features

#33 Fix authentication bugs
  lib/components/nav_drawer.dart
  lib/models/user.dart
  lib/pages/test_page1.dart
  lib/providers/user_provider.dart
  lib/services/auth_service.dart
  lib/services/user_position_service.dart
  lib/utils/constants.dart
  server/handlers/auth/authSignUpHandler.ts
Labels: bug

#37 Add reset account balance
  lib/models/user_position.dart
  lib/pages/home_page.dart
  lib/providers/user_position_provider.dart
Labels: core features

#39 Feature/issue 31/api db crud endpoints
  lib/bloc/nav_drawer/nav_drawer_state.dart
  lib/components/candlestick_chart.dart
  lib/components/chart_data_point.dart
  lib/components/nav_drawer.dart
  lib/components/stock_card.dart
  lib/main.dart
  lib/models/account_position.dart
  lib/models/user.dart
  lib/pages/home_page.dart
  lib/pages/search_page.dart
  lib/pages/sign_in_page.dart
  lib/pages/sign_up_page.dart
  lib/pages/stock_details_page.dart
  lib/services/alpaca_service.dart
  lib/services/user_position_service.dart
  lib/ui/ui_colours.dart
  lib/ui/ui_text.dart
  lib/utils/constants.dart
  server/__tests__/handlers/userDataHandlers/userPositionHandlers.test.ts
  server/handlers/auth/index.ts
  server/handlers/userdata/buyStockHandler.ts
  server/handlers/userdata/getUserPositionHandler.ts
  server/handlers/userdata/index.ts
  server/handlers/userdata/resetUserBalance.ts
  server/handlers/userdata/sellStockHandler.ts
  server/models/userPosition.ts
  server/routes/auth.ts
  server/routes/user.ts
Labels: core features

#43 Feature/issue 12/news function
  lib/components/candlestick_chart.dart
  lib/components/news_article.dart
  lib/pages/stock_details_page.dart
  lib/services/alpaca_service.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: core features

#46 Added different chart types
  lib/components/auth_text_field.dart
  lib/components/candle_chart.dart
  lib/components/chart_type.dart
  lib/components/line_chart.dart
  lib/main.dart
  lib/pages/home_page.dart
  lib/pages/search_page.dart
  lib/pages/stock_details_page.dart
  lib/services/alpaca_service.dart
  lib/utils/constants.dart
Labels: core features

#48 Feature/issue 47/market movers
  assets/images/Group_17.png
  assets/images/Group_21.png
  assets/images/Group_23.png
  assets/images/Group_24.png
  lib/components/chart_type.dart
  lib/components/line_chart.dart
  lib/core/authentication/components/auth_button.dart
  lib/core/authentication/components/auth_text_field.dart
  lib/core/authentication/pages/sign_in_page.dart
  lib/core/authentication/pages/sign_up_page.dart
  lib/core/home/home_page.dart
  lib/core/home/stock_card.dart
  lib/core/navigation/bloc/nav_drawer_bloc.dart
  lib/core/navigation/bloc/nav_drawer_event.dart
  lib/core/navigation/bloc/nav_drawer_state.dart
  lib/core/navigation/components/nav_drawer.dart
  lib/core/navigation/pages/main_wrapper.dart
  lib/core/search/search_page.dart
  lib/core/stock/charts/chart_data_point.dart
  lib/core/stock/charts/custom_interactive_tooltip.dart
  lib/core/stock/charts/custom_trackball_behaviour.dart
  lib/core/stock/charts/custom_x_axis.dart
  lib/core/stock/charts/custom_y_axis.dart
  lib/core/stock/charts/custom_zoom_pan_behaviour.dart
  lib/core/stock/components/candle_chart.dart
  lib/core/stock/components/line_chart.dart
  lib/core/stock/components/news_article.dart
  lib/core/stock/components/stock_metrics_panel.dart
  lib/core/stock/components/trade_panel.dart
  lib/core/stock/pages/stock_details_page.dart
  lib/core/trending/market_movers_page.dart
  lib/core/trending/mover_card.dart
  lib/core/trending/mover_chart.dart
  lib/main.dart
  lib/models/user.dart
  lib/pages/stock_details_page.dart
  lib/pages/test_page2.dart
  lib/pages/test_page3.dart
  lib/services/alpaca_service.dart
  lib/services/auth_service.dart
  lib/ui/ui_colours.dart
  lib/ui/ui_text.dart
  lib/utils/constants.dart
  pubspec.yaml
Labels: core features

#49 Feature/issue 40/add transaction history
  lib/core/home/components/position_card.dart
  lib/core/home/pages/home_page.dart
  lib/core/navigation/bloc/nav_drawer_state.dart
  lib/core/navigation/components/nav_drawer.dart
  lib/core/navigation/pages/main_wrapper.dart
  lib/core/stock/components/trade_panel.dart
  lib/core/stock/pages/stock_details_page.dart
  lib/core/transaction/transaction_card.dart
  lib/models/transaction.dart
  lib/pages/transaction_history_page.dart
  lib/services/auth_service.dart
  lib/services/transaction_service.dart
  lib/services/user_position_service.dart
  lib/utils/constants.dart
  server/handlers/auth/authJWTTokenHandler.ts
  server/handlers/auth/authSignInHandler.ts
  server/handlers/auth/authSignUpHandler.ts
  server/handlers/auth/authTokenIsValidHandler.ts
  server/handlers/transactionHistory/addTransactionHandler.ts
  server/handlers/transactionHistory/getTransactionHistoryHandler.ts
  server/handlers/transactionHistory/index.ts
  server/handlers/transactionHistory/resetTransactionHistory.ts
  server/handlers/userdata/buyStockHandler.ts
  server/handlers/userdata/getUserPositionHandler.ts
  server/handlers/userdata/resetUserBalance.ts
  server/handlers/userdata/sellStockHandler.ts
  server/index.ts
  server/models/index.ts
  server/models/transaction.ts
  server/routes/transaction.ts
  server/yarn.lock
Labels: core features

#54 Feature/issue 40/add transaction history
  .gitignore
  lib/core/home/components/position_card.dart
  lib/core/home/pages/home_page.dart
  lib/core/navigation/bloc/nav_drawer_state.dart
  lib/core/navigation/components/nav_drawer.dart
  lib/core/navigation/pages/main_wrapper.dart
  lib/core/stock/components/trade_panel.dart
  lib/core/stock/pages/stock_details_page.dart
  lib/core/transaction/transaction_card.dart
  lib/models/transaction.dart
  lib/pages/transaction_history_page.dart
  lib/services/auth_service.dart
  lib/services/transaction_service.dart
  lib/services/user_position_service.dart
  lib/utils/constants.dart
  server/handlers/auth/authJWTTokenHandler.ts
  server/handlers/auth/authSignInHandler.ts
  server/handlers/auth/authSignUpHandler.ts
  server/handlers/auth/authTokenIsValidHandler.ts
  server/handlers/transactionHistory/addTransactionHandler.ts
  server/handlers/transactionHistory/getTransactionHistoryHandler.ts
  server/handlers/transactionHistory/index.ts
  server/handlers/transactionHistory/resetTransactionHistory.ts
  server/handlers/userdata/buyStockHandler.ts
  server/handlers/userdata/getUserPositionHandler.ts
  server/handlers/userdata/resetUserBalance.ts
  server/handlers/userdata/sellStockHandler.ts
  server/index.ts
  server/models/index.ts
  server/models/transaction.ts
  server/package-lock.json
  server/package.json
  server/routes/transaction.ts
  server/yarn.lock
Labels: bug, core features

#58 Resolve bug
  lib/core/home/pages/home_page.dart
Labels: bug, core features

#60 Add unit tests for handlers added
  lib/core/home/pages/home_page.dart
  lib/core/stock/components/trade_panel.dart
  lib/services/user_position_service.dart
  package-lock.json
  package.json
  pubspec.lock
  pubspec.yaml
  server/__tests__/handlers/transactionHistoryHandlers/addTransactionHandler.test.ts
  server/__tests__/handlers/transactionHistoryHandlers/getTransactionHistoryHandler.test.ts
  server/__tests__/handlers/transactionHistoryHandlers/resetTransactionHistoryHandler.test.ts
  server/__tests__/handlers/userDataHandlers/buyStockHandler.test.ts
  server/__tests__/handlers/userDataHandlers/getUserPositionHandler.test.ts
  server/__tests__/handlers/userDataHandlers/resetUserBalanceHandler.test.ts
  server/__tests__/handlers/userDataHandlers/sellStockHandler.test.ts
Labels: testing
